### PR TITLE
Temperature rading update

### PR DESCRIPTION
**Pull request by MarBasso**
I made an update with correct temperature rading, according with "Temperature Registers" chapter of DS3232 datasheet. I don't know if it's the best way to do it but I hadn't other ideas. Code and data have been tested and compared with DS1820 temperature sensor.
Now the function "temperature()" returns a float number with sign and 2 fractional digits (DS3232 has a temperature sensitivity of 0.25°C so the temperature value is on 0.25 steps).

I also included a redefinition of TEMP_LSB and TEMP_MSB in TEMP_RTC_LSB and TEMP_RTC_MSB to avoid possible conflicts with DallasTemperature library (though I've never had problems whit original defines during the comparison test with both devices connected on the same Arduino, don't know why).

### CODE REVIEW

**Comment by MarBasso** [comment]
PS. This is my first pull request, sorry if I made something wrong in some step. For what I know, I could have broken GitHub servers! :laughing:

**Comment by JChristensen** [comment]
Thanks but a main design consideration for this library was to keep it small; the reason for operating in the integer domain was to avoid the overhead of loading the floating point library. I recognize that this may not be everyone's cup of tea but that's the nice thing about GitHub, anyone can fork the library and modify it to fit their requirements.

**Comment by JChristensen** [comment]
PS: By changing the library to return a float instead of an integer, this would not be backwards compatible for people already using the library, they would need to change their code. Instead, I would consider: (1) Adding a function to return the temperature as floating point, or (2) Writing a derived class to do the same.

**Comment by MarBasso** [comment]
Ok, thank you for the explaination and mostly for yours and contributors work! I didn't know the reasons why to don't add the full temperature extraction and I agree with you in all the points.

Regarding the lightweight of this library (and the correct intuition of don't load the float lib), maybe an useful improvement can be to avoid the division by 4 once obtained the int value. This can be made by reading the only TEMP_MSB value: it is already the integer portion of the temperature. Then a final addition can be the management of the sign contained in TEMP_MSB (I gess that even in your code a negative chip temperature leads to a wrong user value).

If you think that this could be useful I can make a new commit modifing your dev fork (as I did for my previous work).

Thanks again!

**Comment by JChristensen** [comment]
The full temperature is indeed returned, just as an integer. The temperature register is simply a two's-complement integer. I don't know what makes you suspect an issue with negative temperatures, but I think that if you will test it, you will find that it works correctly. There is little to be gained by not returning the LSB, perhaps a few bytes of code. Although given the rather dismal accuracy of the RTC's temperature sensor (±3℃) it's not a completely unreasonable argument.
PS: Don't forget to also update the ReadMe file in your fork.

**Comment by MarBasso** [comment]
So, just to understand, the role of the temperature() function is to give the user a raw (int) value to be processed to get what he wants, right? For example, if I only care about the integer number I divide it for 4, if I even want the fractional value I have to apply some boolean logic (besides being finicky :smile: ). That's right?
About the negative value..... I read just now that it's in two's complement format! Maybe when I read the first time I missed the most important line.. :cold_sweat: :see_no_evil: .

I'm using this function of the chip (with the main time and date functions) because I'm building a water irrigation system for pot plants and I'm trying to get as much as I can without adding other modules (I even have an LCD, a pump and several soil moisture sensors to manage). I think that the poor temperature sensor of the DS3232 should be enough to have an idea of what's happening in the ambient and acting by consequence (for example notifying if temperature is near zero or if it's going too high).

**Pull request closed without merging**
