### PR TITLE
Add new method readAlarm()

### PR DESCRIPTION
**Pull request by PRosenb**
It is sometimes useful to read back the set alarms from the device. To do that, I added the readAlarm() method.

### CODE REVIEW

**Comment by PeterRosenberg** [comment]
Please apply pull request #15  before mine as my change bases on it.

**Comment by ujjaldey** [comment]
Hi,

Thanks for the useful method. But I am stuck at one issue.

I have set an alarm as:

```RTC.setAlarm(ALM2_MATCH_HOURS, 57, 01, 0);```

So next time it would be triggered at 24-Jan-2016, 01:57 hrs.

But when I am trying to read the alarm and printing the output,

```
tmElements_t alarm;
RTC.readAlarm(ALARM_2, alarm);
```

I am getting the output as below:
> next dd 0 mon 244 yyyy 6 hh 1 min 57 sec 0

However I want the output to be
> next dd 24 mon 1 yyyy 2016 hh 1 min 57 sec 0

Am I making any mistake? Can you please help? Many thanks in advance.

**Comment by PeterRosenberg** [comment]
Hi ujjaldey,
The method `readAlarm()` does not return the time of the next alarm, it returns you the settings in the RTC chip, filled into the `tmElements_t `struct.
It allows you to read back what you have written with the `setAlarm()` call so that you don't need to store these values.
Therefore, `readAlarm()` returns the values you set when calling  `setAlarm()`. This means that `readAlarm()` only uses the following members in `tmElements_t`:
`Wday,` `Day`, `Hour`, `Minute`, `Second`

**Comment by PRosenb** [comment]
@JChristensen How long time do you give yourself to decide on pull requests? All four pull request are open now for a long time already..

**Pull request closed without merging**
