### PR TITLE
switch to avr-libc time library

### PR DESCRIPTION
**Pull request by raburton**
no need for external time library, requires arduino ide 1.6.10+

### CODE REVIEW

**Comment by JChristensen** [comment]
Not sure I understand.

**Comment by raburton** [comment]
Not sure I understand the previous comment either. Also, out of interest
why was this declined?

**Comment by JChristensen** [comment]
I did not understand, "no need for external time library, requires arduino ide 1.6.10+"
I have quite a backlog I'm trying to work through, so excuse the ruthlessness.

**Comment by raburton** [comment]
It was a while ago, so I'm going from memory... This patch removed the
dependency on an external time library and allowed it to use the standard
compiler time library. However, that was only possible from Arduino IDE of
the stated version.

On 1 Jan 2018 11:19 pm, "Jack Christensen" <notifications@github.com> wrote:

I did not understand, "no need for external time library, requires arduino
ide 1.6.10+"
I have quite a backlog I'm trying to work through, so excuse the
ruthlessness.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JChristensen/DS3232RTC/pull/34#issuecomment-354684145>,
or mute the thread

**Comment by JChristensen** [comment]
That is interesting, but, if it only applied to a particular version of the IDE, then it sounds like a moot point now. It's the sort of thing I'd need to spend significant time investigating as I have multiple libraries and projects that use the Time library. So I'm inclined to not break anything that's not broken. Hope that helps.

**Comment by raburton** [comment]
That's fair enough, it would need testing (although I'm using it happy, doesn't mean I've covered all eventualities). 1.6.10 came out June 2016, so I imagine most people would have that or newer by now.

**Comment by JChristensen** [comment]
Out of curiosity, I did have a quick look at time.h (it's still present in 1.8.5) and it seems significantly different from the de facto standard Arduino Time library, hardly a drop-in replacement. That's not to say that it wouldn't work in certain situations, as you have demonstrated! OTOH it has some interesting functionality like calculating sunrise and sunset. So thanks and Happy New Year!

**Pull request closed without merging**
